name: Kubernetes deployment

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SA }}'

      - run: |
          docker build -t southamerica-west1-docker.pkg.dev/blucore/bluecore-registry/flask-api-service:1.0.0 .
          ocker push southamerica-west1-docker.pkg.dev/blucore/bluecore-registry/flask-api-service:1.0.0

      
