name: Kubernetes deployment

on: 
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: kubectl
      
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SA }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: docker login
        run: |
          gcloud auth configure-docker southamerica-west1-docker.pkg.dev

      - name: Docker build and push
        run: |
          docker build -t southamerica-west1-docker.pkg.dev/blucore/bluecore-registry/flask-api-service:1.0.0 .
          docker push southamerica-west1-docker.pkg.dev/blucore/bluecore-registry/flask-api-service:1.0.0

      - name: Cluster 
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud components list
          echo -----
          gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project blucore

      - name: Deploy K8s
        run: |
          kubectl get all
          #kubectl apply -f k8s
          #kubectl get all
          
